In [38]:
import pandas as pd
import numpy as np

In [39]:
states=[(0,''), (0,'1'), (0,'2'), (0,'3'), (0, '12'), (0,'13'), (0,'23'), (0,'123'),
        (1,''), (1,'1'), (1,'2'), (3,'3'), (1, '12'), (1,'13'), (1,'23'), (1,'123'),
        (2,''), (2,'1'), (2,'2'), (2,'3'), (2, '12'), (2,'13'), (2,'23'),(2,'123')]

In [40]:
from IPython.display import display
a=np.array([i[0]+len(i[1])+1 for i in states if isinstance(i[0], int)])
b=np.array([i[0]+len(i[1]) for i in states if isinstance(i[0], int)])
R=pd.DataFrame(np.subtract.outer(a,b))
R[R<0]=0
R

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,3,2,2,2,1,1,1,0,2,1,...,0,0,1,0,0,0,0,0,0,0
5,3,2,2,2,1,1,1,0,2,1,...,0,0,1,0,0,0,0,0,0,0
6,3,2,2,2,1,1,1,0,2,1,...,0,0,1,0,0,0,0,0,0,0
7,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
8,2,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,3,2,2,2,1,1,1,0,2,1,...,0,0,1,0,0,0,0,0,0,0
10,3,2,2,2,1,1,1,0,2,1,...,0,0,1,0,0,0,0,0,0,0
11,5,4,4,4,3,3,3,2,4,3,...,2,1,3,2,2,2,1,1,1,0
12,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
13,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
14,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
15,5,4,4,4,3,3,3,2,4,3,...,2,1,3,2,2,2,1,1,1,0
16,3,2,2,2,1,1,1,0,2,1,...,0,0,1,0,0,0,0,0,0,0
17,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
18,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
19,4,3,3,3,2,2,2,1,3,2,...,1,0,2,1,1,1,0,0,0,0
20,5,4,4,4,3,3,3,2,4,3,...,2,1,3,2,2,2,1,1,1,0
21,5,4,4,4,3,3,3,2,4,3,...,2,1,3,2,2,2,1,1,1,0
22,5,4,4,4,3,3,3,2,4,3,...,2,1,3,2,2,2,1,1,1,0
23,6,5,5,5,4,4,4,3,5,4,...,3,2,4,3,3,3,2,2,2,1

In [41]:
R.columns=states
R.index=states

/usr/local/lib/python3.5/dist-packages/pandas/indexes/api.py:71: RuntimeWarning: unorderable types: tuple() < int(), sort order is undefined for incomparable objects
  result = result.union(other)

,"(0, )","(0, 1)","(0, 2)","(0, 3)","(0, 12)","(0, 13)","(0, 23)","(0, 123)","(1, )","(1, 1)",...,14,15,16,17,18,19,20,21,22,23
"(0, )",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 1)",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 2)",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 3)",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 12)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 13)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 23)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(0, 123)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, )",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, 1)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, 2)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(3, 3)",5.0,4.0,4.0,4.0,3.0,3.0,3.0,2.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, 12)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, 13)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, 23)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, 123)",5.0,4.0,4.0,4.0,3.0,3.0,3.0,2.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, )",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 1)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 2)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 3)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 12)",5.0,4.0,4.0,4.0,3.0,3.0,3.0,2.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 13)",5.0,4.0,4.0,4.0,3.0,3.0,3.0,2.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 23)",5.0,4.0,4.0,4.0,3.0,3.0,3.0,2.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, 123)",6.0,5.0,5.0,5.0,4.0,4.0,4.0,3.0,5.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
from IPython.display import display
a=np.array([i[0]+len(i[1])+1 for i in R.index if isinstance(i[0], int)])
b=np.array([i[0]+len(i[1]) for i in R.index if isinstance(i[0], int)])
R=pd.DataFrame(np.subtract.outer(a,b))

In [21]:
#From No outs to everything else
R.iloc[0,:]=[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.iloc[1,:]=[2,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.iloc[2,:]=[2,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(0,3)',:]=[2,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(0,12)',:]=[3,2,2,2,1,1,1,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(0,13)',:]=[3,2,2,2,1,1,1,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(0,23)',:]=[3,2,2,2,1,1,1,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(0,123)',:]=[4,3,3,3,2,2,2,1,3,2,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(1,0)',:]=[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(1,1)',:]=[0,0,0,0,0,0,0,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(1,2)',:]=[0,0,0,0,0,0,0,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(1,3)',:]=[0,0,0,0,0,0,0,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
R.ix['(1,12)',:]=[0,0,0,0,0,0,0,0,3,2,2,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [22]:
R

,"(0,0)","(0,1)","(0,2)","(0,3)","(0, 12)","(0,13)","(0,23)","(0,123)","(1,0)","(1,1)",...,"(2,2)","(2,3)","(2, 12)","(2,13)","(2,23)","(2,123)","(3,A)","(3,B)","(3,C)","(3,D)"
"(0,0)",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,1)",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,2)",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,3)",2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0, 12)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,13)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,23)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,123)",4.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,3.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1,0)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1,1)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1,2)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(3,3)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1, 12)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1,13)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1,23)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(1,123)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,0)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,1)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,2)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,3)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2, 12)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,13)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,23)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(2,123)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(3,A)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(3,B)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(3,C)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(3,D)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(0,12)",3.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
[i for i in R.index]

['(0,0)',
 '(0,1)',
 '(0,2)',
 '(0,3)',
 '(0, 12)',
 '(0,13)',
 '(0,23)',
 '(0,123)',
 '(1,0)',
 '(1,1)',
 '(1,2)',
 '(3,3)',
 '(1, 12)',
 '(1,13)',
 '(1,23)',
 '(1,123)',
 '(2,0)',
 '(2,1)',
 '(2,2)',
 '(2,3)',
 '(2, 12)',
 '(2,13)',
 '(2,23)',
 '(2,123)',
 '(3,A)',
 '(3,B)',
 '(3,C)',
 '(3,D)',
 '(0,12)']